Numpy tests plus a little vector db 

In [17]:
import numpy as np 

# From rector.py
db = np.array([
    [0.1, 0.3, 0.7, 0.9],
    [0.2, 0.1, 0.4, 0.8],
    [0.9, 0.8, 0.3, 0.2],
    [0.4, 0.4, 0.6, 0.7],
    [0.7, 0.9, 0.1, 0.2]
])

query = np.array([0.3, 0.2, 0.8, 0.9])

def cosine_similarity(a,b):
  return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# 
def search(query, db, top_k=1):
    # cosine somiliraity compution 
    similarities = [cosine_similarity(query, v) for v in db]
    # argsort gives lowest to highest, [::-1] revers that to highest first
    sorted_idx = np.argsort(similarities)[::-1]  
    # top_k=2 get theb est two rows and their cosine scores
    return [(i, similarities[i]) for i in sorted_idx[:top_k]]

results = search(query, db)
print("Top results:", results)


# cosine similarity in simple terms 
# multiply matching positions and add them upp (dot product)
# find the length of each vector (square each value, add, square root)
# divide the dot product by (length of a x length of b)
# bigger results closer to 1 mans more similar directorion 




# it measuers how similar two vectors are by the angle between them. same direction = 1, 0 is unrelated opposite is -1
# dot product, line up the numbers, multiply in pairs, then add.
#  [a, b, c] · [d, e, f] = a·d + b·e + c·f.
# length of each vector, square each number, then add then square root. 
# Length([a, b, c]) = sqrt(a² + b² + c²).
# cosine similarity is the dot products / (length of first x length of second )

Top results: [(np.int64(0), np.float64(0.9816581904580174))]


In [18]:

import numpy as np 

vector_column = np.array([[1], [2], [3]])
print(vector_column)

# Note: the original np.matrix string is malformed; fixing it to a proper 3x4 matrix
mat1 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat1)

print(mat1.shape[0])



[[1]
 [2]
 [3]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
3
